### ISSUE TITLE
Make environment settings optional

### ISSUE THREAD

**Issue by zzak** [firestormforum/firestorm#131]
In order to boot the app you have to set the following variables:

```
# AWS_ACCESS_KEY_ID=TKTK
# AWS_SECRET_ACCESS_KEY=TKTK
# AWS_S3_BUCKET=TKTK
# AWS_S3_REGION=TKTK
# GITHUB_CLIENT_ID=TKTK
# GITHUB_CLIENT_SECRET=TKTK
# SENDGRID_API_KEY=TKTK
```
It's great this is documented, but not great that I need to set them (even to dummy values) to get the tests to run.

After that I **was able** to [build the app on CircleCI](https://circleci.com/gh/CircleCI-Public/firestorm), but this was the only catch.

**Comment by zzak** [comment]
Additionally, would you be interested in converting this project to run on CircleCI?

Open-source projects get 4 containers for their builds.

**Comment by knewter** [comment]
I don't want to change CI providers atm just because I have a level of familiarity with what i'm using, though i'm not against it in the future. But I would love to have a PR that makes it possible to run the tests without the env vars set - would really just need to provide a default value for each of them in config/test.exs. Do you want to send a PR in @zzak ? I'm glad to help a ton on it if needed / helpful

**Comment by zzak** [comment]
@knewter Sounds good, thanks for getting back to me!

This was sitting in my backlog when I setup the demo project, and wanted to make sure I filed it in the right place.

I'll send over a PR! :bow:
